import { Transaction } from "./store";

export const initialTransactions: Transaction[] = [
  // ── APRIL 2026 (current month) ──────────────────────────────
  {
    id: "tx-apr-1",
    date: "2026-04-03",
    description: "April Salary",
    category: "Salary",
    type: "income",
    amount: 5800.00,
    status: "completed",
  },
  {
    id: "tx-apr-2",
    date: "2026-04-02",
    description: "Grocery Store",
    category: "Food",
    type: "expense",
    amount: 162.40,
    status: "completed",
  },
  {
    id: "tx-apr-3",
    date: "2026-04-02",
    description: "Apartment Rent",
    category: "Rent",
    type: "expense",
    amount: 1900.00,
    status: "completed",
  },
  {
    id: "tx-apr-4",
    date: "2026-04-01",
    description: "Electric & Internet Bill",
    category: "Bills",
    type: "expense",
    amount: 118.00,
    status: "completed",
  },
  {
    id: "tx-apr-5",
    date: "2026-04-01",
    description: "Coffee Shop",
    category: "Food",
    type: "expense",
    amount: 18.50,
    status: "completed",
  },
  {
    id: "tx-apr-6",
    date: "2026-04-01",
    description: "Gym Membership",
    category: "Health",
    type: "expense",
    amount: 55.00,
    status: "completed",
  },
  {
    id: "tx-apr-7",
    date: "2026-04-01",
    description: "Online Shopping (Amazon)",
    category: "Shopping",
    type: "expense",
    amount: 245.00,
    status: "completed",
  },
  {
    id: "tx-apr-8",
    date: "2026-04-01",
    description: "Freelance Web Project",
    category: "Freelance",
    type: "income",
    amount: 1400.00,
    status: "completed",
  },
  {
    id: "tx-apr-9",
    date: "2026-04-01",
    description: "Netflix & Spotify",
    category: "Entertainment",
    type: "expense",
    amount: 32.00,
    status: "completed",
  },
  {
    id: "tx-apr-10",
    date: "2026-04-01",
    description: "Uber Rides",
    category: "Travel",
    type: "expense",
    amount: 48.00,
    status: "completed",
  },

  // ── MARCH 2026 ────────────────────────────────────────────────
  {
    id: "tx-mar-1",
    date: "2026-03-28",
    description: "March Salary",
    category: "Salary",
    type: "income",
    amount: 5800.00,
    status: "completed",
  },
  {
    id: "tx-mar-2",
    date: "2026-03-27",
    description: "Restaurant Dinner",
    category: "Food",
    type: "expense",
    amount: 78.90,
    status: "completed",
  },
  {
    id: "tx-mar-3",
    date: "2026-03-25",
    description: "Apartment Rent",
    category: "Rent",
    type: "expense",
    amount: 1900.00,
    status: "completed",
  },
  {
    id: "tx-mar-4",
    date: "2026-03-22",
    description: "Flight to Mumbai",
    category: "Travel",
    type: "expense",
    amount: 520.00,
    status: "completed",
  },
  {
    id: "tx-mar-5",
    date: "2026-03-20",
    description: "Grocery Store",
    category: "Food",
    type: "expense",
    amount: 145.20,
    status: "completed",
  },
  {
    id: "tx-mar-6",
    date: "2026-03-18",
    description: "Freelance Design Work",
    category: "Freelance",
    type: "income",
    amount: 900.00,
    status: "completed",
  },
  {
    id: "tx-mar-7",
    date: "2026-03-15",
    description: "Doctor Visit",
    category: "Health",
    type: "expense",
    amount: 95.00,
    status: "completed",
  },
  {
    id: "tx-mar-8",
    date: "2026-03-12",
    description: "Online Course (Udemy)",
    category: "Education",
    type: "expense",
    amount: 49.99,
    status: "completed",
  },
  {
    id: "tx-mar-9",
    date: "2026-03-10",
    description: "Electric Bill",
    category: "Bills",
    type: "expense",
    amount: 102.00,
    status: "completed",
  },
  {
    id: "tx-mar-10",
    date: "2026-03-05",
    description: "New Shoes",
    category: "Shopping",
    type: "expense",
    amount: 189.00,
    status: "completed",
  },
  {
    id: "tx-mar-11",
    date: "2026-03-03",
    description: "Movie & Popcorn",
    category: "Entertainment",
    type: "expense",
    amount: 28.50,
    status: "completed",
  },

  // ── FEBRUARY 2026 ─────────────────────────────────────────────
  {
    id: "tx-feb-1",
    date: "2026-02-28",
    description: "February Salary",
    category: "Salary",
    type: "income",
    amount: 5800.00,
    status: "completed",
  },
  {
    id: "tx-feb-2",
    date: "2026-02-25",
    description: "Apartment Rent",
    category: "Rent",
    type: "expense",
    amount: 1900.00,
    status: "completed",
  },
  {
    id: "tx-feb-3",
    date: "2026-02-20",
    description: "Valentine's Dinner",
    category: "Food",
    type: "expense",
    amount: 135.00,
    status: "completed",
  },
  {
    id: "tx-feb-4",
    date: "2026-02-18",
    description: "Gift for Partner",
    category: "Shopping",
    type: "expense",
    amount: 220.00,
    status: "completed",
  },
  {
    id: "tx-feb-5",
    date: "2026-02-15",
    description: "Gym Membership",
    category: "Health",
    type: "expense",
    amount: 55.00,
    status: "completed",
  },
  {
    id: "tx-feb-6",
    date: "2026-02-12",
    description: "Freelance App Project",
    category: "Freelance",
    type: "income",
    amount: 2100.00,
    status: "completed",
  },
  {
    id: "tx-feb-7",
    date: "2026-02-10",
    description: "Internet & Phone Bill",
    category: "Bills",
    type: "expense",
    amount: 85.00,
    status: "completed",
  },
  {
    id: "tx-feb-8",
    date: "2026-02-06",
    description: "Grocery Store",
    category: "Food",
    type: "expense",
    amount: 128.60,
    status: "completed",
  },
  {
    id: "tx-feb-9",
    date: "2026-02-03",
    description: "Concert Tickets",
    category: "Entertainment",
    type: "expense",
    amount: 95.00,
    status: "completed",
  },

  // ── JANUARY 2026 ──────────────────────────────────────────────
  {
    id: "tx-jan-1",
    date: "2026-01-31",
    description: "January Salary",
    category: "Salary",
    type: "income",
    amount: 5800.00,
    status: "completed",
  },
  {
    id: "tx-jan-2",
    date: "2026-01-25",
    description: "Apartment Rent",
    category: "Rent",
    type: "expense",
    amount: 1900.00,
    status: "completed",
  },
  {
    id: "tx-jan-3",
    date: "2026-01-22",
    description: "New Year Shopping",
    category: "Shopping",
    type: "expense",
    amount: 340.00,
    status: "completed",
  },
  {
    id: "tx-jan-4",
    date: "2026-01-18",
    description: "Flight to Goa",
    category: "Travel",
    type: "expense",
    amount: 680.00,
    status: "completed",
  },
  {
    id: "tx-jan-5",
    date: "2026-01-15",
    description: "Grocery Store",
    category: "Food",
    type: "expense",
    amount: 155.80,
    status: "completed",
  },
  {
    id: "tx-jan-6",
    date: "2026-01-12",
    description: "Annual Health Checkup",
    category: "Health",
    type: "expense",
    amount: 210.00,
    status: "completed",
  },
  {
    id: "tx-jan-7",
    date: "2026-01-08",
    description: "Electric Bill",
    category: "Bills",
    type: "expense",
    amount: 125.00,
    status: "completed",
  },
  {
    id: "tx-jan-8",
    date: "2026-01-05",
    description: "Freelance Report Writing",
    category: "Freelance",
    type: "income",
    amount: 650.00,
    status: "completed",
  },

  // ── DECEMBER 2025 ─────────────────────────────────────────────
  {
    id: "tx-dec-1",
    date: "2025-12-31",
    description: "December Salary",
    category: "Salary",
    type: "income",
    amount: 5800.00,
    status: "completed",
  },
  {
    id: "tx-dec-2",
    date: "2025-12-28",
    description: "Christmas Gifts",
    category: "Shopping",
    type: "expense",
    amount: 420.00,
    status: "completed",
  },
  {
    id: "tx-dec-3",
    date: "2025-12-25",
    description: "Apartment Rent",
    category: "Rent",
    type: "expense",
    amount: 1900.00,
    status: "completed",
  },
  {
    id: "tx-dec-4",
    date: "2025-12-20",
    description: "Holiday Dinner",
    category: "Food",
    type: "expense",
    amount: 195.00,
    status: "completed",
  },
  {
    id: "tx-dec-5",
    date: "2025-12-17",
    description: "Year-End Bonus",
    category: "Salary",
    type: "income",
    amount: 2000.00,
    status: "completed",
  },
  {
    id: "tx-dec-6",
    date: "2025-12-12",
    description: "Pharmacy & Vitamins",
    category: "Health",
    type: "expense",
    amount: 68.00,
    status: "completed",
  },
  {
    id: "tx-dec-7",
    date: "2025-12-08",
    description: "Disney+ & Apple TV",
    category: "Entertainment",
    type: "expense",
    amount: 42.00,
    status: "completed",
  },
  {
    id: "tx-dec-8",
    date: "2025-12-05",
    description: "Electric Bill",
    category: "Bills",
    type: "expense",
    amount: 138.00,
    status: "completed",
  },
  {
    id: "tx-dec-9",
    date: "2025-12-03",
    description: "Freelance Logo Design",
    category: "Freelance",
    type: "income",
    amount: 800.00,
    status: "completed",
  },

  // ── NOVEMBER 2025 ─────────────────────────────────────────────
  {
    id: "tx-nov-1",
    date: "2025-11-30",
    description: "November Salary",
    category: "Salary",
    type: "income",
    amount: 5800.00,
    status: "completed",
  },
  {
    id: "tx-nov-2",
    date: "2025-11-25",
    description: "Apartment Rent",
    category: "Rent",
    type: "expense",
    amount: 1900.00,
    status: "completed",
  },
  {
    id: "tx-nov-3",
    date: "2025-11-22",
    description: "Black Friday Shopping",
    category: "Shopping",
    type: "expense",
    amount: 510.00,
    status: "completed",
  },
  {
    id: "tx-nov-4",
    date: "2025-11-18",
    description: "Grocery Store",
    category: "Food",
    type: "expense",
    amount: 142.00,
    status: "completed",
  },
  {
    id: "tx-nov-5",
    date: "2025-11-14",
    description: "Phone Bill",
    category: "Bills",
    type: "expense",
    amount: 75.00,
    status: "completed",
  },
  {
    id: "tx-nov-6",
    date: "2025-11-10",
    description: "Weekend Getaway",
    category: "Travel",
    type: "expense",
    amount: 380.00,
    status: "completed",
  },
  {
    id: "tx-nov-7",
    date: "2025-11-05",
    description: "Gym Membership",
    category: "Health",
    type: "expense",
    amount: 55.00,
    status: "completed",
  },
  {
    id: "tx-nov-8",
    date: "2025-11-03",
    description: "Freelance Data Analysis",
    category: "Freelance",
    type: "income",
    amount: 1200.00,
    status: "completed",
  },

  // ── OCTOBER 2025 ──────────────────────────────────────────────
  {
    id: "tx-oct-1",
    date: "2025-10-31",
    description: "October Salary",
    category: "Salary",
    type: "income",
    amount: 5800.00,
    status: "completed",
  },
  {
    id: "tx-oct-2",
    date: "2025-10-28",
    description: "Apartment Rent",
    category: "Rent",
    type: "expense",
    amount: 1900.00,
    status: "completed",
  },
  {
    id: "tx-oct-3",
    date: "2025-10-25",
    description: "Halloween Party Supplies",
    category: "Shopping",
    type: "expense",
    amount: 95.00,
    status: "completed",
  },
  {
    id: "tx-oct-4",
    date: "2025-10-20",
    description: "Grocery Store",
    category: "Food",
    type: "expense",
    amount: 138.00,
    status: "completed",
  },
  {
    id: "tx-oct-5",
    date: "2025-10-15",
    description: "Electric & Internet Bill",
    category: "Bills",
    type: "expense",
    amount: 108.00,
    status: "completed",
  },
  {
    id: "tx-oct-6",
    date: "2025-10-10",
    description: "Cinema & Dining",
    category: "Entertainment",
    type: "expense",
    amount: 72.00,
    status: "completed",
  },
  {
    id: "tx-oct-7",
    date: "2025-10-08",
    description: "Freelance Content Writing",
    category: "Freelance",
    type: "income",
    amount: 550.00,
    status: "completed",
  },
  {
    id: "tx-oct-8",
    date: "2025-10-05",
    description: "Annual Gym Membership",
    category: "Health",
    type: "expense",
    amount: 480.00,
    status: "completed",
  },
];
